@echo off
REM 🚂 Railway PostgreSQL Deployment Script for Windows
REM This script deploys your Django app to Railway with PostgreSQL database

echo 🚂 Starting Railway deployment with PostgreSQL...

REM Check if Railway CLI is installed
railway --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Railway CLI not found. Please install it first:
    echo    npm install -g @railway/cli
    echo    or visit: https://docs.railway.app/develop/cli
    pause
    exit /b 1
)

REM Login to Railway (if not already logged in)
echo 🔐 Checking Railway authentication...
railway whoami
if %errorlevel% neq 0 (
    echo Please login to Railway:
    railway login
)

REM Set environment variables for production
echo 🔧 Setting up environment variables...

REM Core Django settings
railway variables set DEBUG=False
railway variables set DJANGO_SECRET_KEY=your-production-secret-key-change-this

REM Database URL (Railway PostgreSQL - this will be auto-generated by Railway)
railway variables set DATABASE_URL=%DATABASE_URL%

REM Payment settings
echo 💳 Setting payment configuration...
railway variables set STRIPE_PUBLISHABLE_KEY=your-stripe-publishable-key
railway variables set STRIPE_SECRET_KEY=your-stripe-secret-key

REM Email settings
echo 📧 Setting email configuration...
railway variables set EMAIL_HOST_USER=your-email-host-user
railway variables set EMAIL_HOST_PASSWORD=your-email-host-password
railway variables set DEFAULT_FROM_EMAIL="ENTstore <your-email@domain.com>"
railway variables set ADMIN_EMAIL=your-admin@email.com

REM Deploy to Railway
echo 🚀 Deploying to Railway...
railway up

echo ✅ Deployment initiated!
echo.
echo 📋 Next steps:
echo 1. Check deployment status: railway status
echo 2. View logs: railway logs
echo 3. Open your app: railway open
echo.
echo 🔗 Your app will be available at: https://your-app.up.railway.app
echo.
echo ⚠️  Important: Make sure you have a PostgreSQL service added to your Railway project!
echo    If not, add it from the Railway dashboard: https://railway.app/dashboard

pause