#!/bin/bash

# 🚂 Railway PostgreSQL Deployment Script
# This script deploys your Django app to Railway with PostgreSQL database

echo "🚂 Starting Railway deployment with PostgreSQL..."

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "❌ Railway CLI not found. Please install it first:"
    echo "   npm install -g @railway/cli"
    echo "   or visit: https://docs.railway.app/develop/cli"
    exit 1
fi

# Login to Railway (if not already logged in)
echo "🔐 Checking Railway authentication..."
railway whoami || {
    echo "Please login to Railway:"
    railway login
}

# Set environment variables for production
echo "🔧 Setting up environment variables..."

# Core Django settings
railway variables set DEBUG=False
railway variables set DJANGO_SECRET_KEY="$(openssl rand -base64 32)"

# Database URL (Railway PostgreSQL - this will be auto-generated by Railway)
railway variables set DATABASE_URL="$DATABASE_URL"

# Payment settings (you'll need to update these with your actual keys)
echo "💳 Setting payment configuration..."
railway variables set STRIPE_PUBLISHABLE_KEY="your-stripe-publishable-key"
railway variables set STRIPE_SECRET_KEY="your-stripe-secret-key"

# Email settings
echo "📧 Setting email configuration..."
railway variables set EMAIL_HOST_USER="your-email-host-user"
railway variables set EMAIL_HOST_PASSWORD="your-email-host-password"
railway variables set DEFAULT_FROM_EMAIL="ENTstore <your-email@domain.com>"
railway variables set ADMIN_EMAIL="your-admin@email.com"

# Deploy to Railway
echo "🚀 Deploying to Railway..."
railway up

echo "✅ Deployment initiated!"
echo ""
echo "📋 Next steps:"
echo "1. Check deployment status: railway status"
echo "2. View logs: railway logs"
echo "3. Open your app: railway open"
echo ""
echo "🔗 Your app will be available at: https://your-app.up.railway.app"
echo ""
echo "⚠️  Important: Make sure you have a PostgreSQL service added to your Railway project!"
echo "   If not, add it from the Railway dashboard: https://railway.app/dashboard"