services:
  # Backend Django API
  - type: web
    name: entstore-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: entstore-db
          property: connectionString
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://entstore-frontend.onrender.com

  # Frontend React/Vite App
  - type: web
    name: entstore-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    startCommand: |
      cd frontend
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://entstore-backend.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false

# Database
databases:
  - name: entstore-db
    databaseName: entstore
    user: entstore_user
    plan: free