services:
  - type: web
    name: entstore-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn myproject.wsgi:application --host 0.0.0.0 --port $PORT"
    disk:
      name: media-storage
      mountPath: /opt/render/project/data
      sizeGB: 1
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: entstore-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: entstore-frontend
          property: host

databases:
  - name: entstore-db
    databaseName: entstore_db
    user: entstore_db_user