[phases.setup]
nixPkgs = ["python311", "postgresql"]

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myproject.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"