# Generated by Django 5.2.4 on 2025-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100),
        ),
    ]
