# Generated by Django 5.2.4 on 2025-09-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Color name (e.g., Red, Blue, Black)', max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size name (e.g., S, M, L, XL)', max_length=10, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the size', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image file', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary product image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity for this specific variant')),
                ('price_adjustment', models.IntegerField(default=0, help_text='Price adjustment in cents (can be negative)')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this variant is available')),
                ('color', models.ForeignKey(help_text='Color of this variant', on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor')),
                ('product', models.ForeignKey(help_text='Product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
                ('size', models.ForeignKey(help_text='Size of this variant', on_delete=django.db.models.deletion.CASCADE, to='shop.productsize')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
