# Generated by Django 5.2.4 on 2025-09-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcolor_productsize_productimage_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Selected product variant (size/color combination)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, help_text='Selected color name (stored as text for historical record)', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Selected size name (stored as text for historical record)', max_length=50),
        ),
    ]
