# Generated by Django 5.2.4 on 2025-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem_product_variant_orderitem_selected_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether the product should be featured on the home page'),
        ),
    ]
