# Generated by Django 5.2.4 on 2025-09-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
