# Generated by Django 5.2.4 on 2025-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_convert_cents_to_dollars_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Promo code (e.g., ENNC10, SUMMER20)', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Description of the promo code', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], default='percentage', help_text='Type of discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount in dollars)', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount required to use this code', max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this code can be used (null = unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promo code is active')),
                ('valid_from', models.DateTimeField(help_text='Date and time when this code becomes valid')),
                ('valid_until', models.DateTimeField(help_text='Date and time when this code expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
