# Generated by Django 5.2.4 on 2025-09-26 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productreview_reviewimage_reviewhelpfulvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=9.99, help_text='Shipping cost for this product in dollars (e.g., 9.99 = $9.99)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
