# Generated by Django 5.2.4 on 2025-10-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product image URL (alternative to uploading files)', null=True),
        ),
    ]
