# Generated by Django 5.2.4 on 2025-10-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_image_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Category image URL (alternative to uploading files)', null=True),
        ),
    ]
