"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%)!&vi67urca4#$_4ia9fft9q_pc+h%5sjal2o!@a9%@f7@4vn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.1.104']

# Railway deployment - add Railway domains
RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
if RAILWAY_STATIC_URL:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)

RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Add known Railway and Render domains
ALLOWED_HOSTS.extend([
    'enontino-production.up.railway.app',
    '*.railway.app',
    '*.up.railway.app',
    '*.onrender.com',
    'entstores.onrender.com',  # Specific Render domain
    'testserver'  # For testing
])

# Ensure Render domain is always allowed
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Allow all hosts in production (Railway and Render will handle the routing)
if not DEBUG:
    ALLOWED_HOSTS = ['*']

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Changed from DENY to allow admin frames
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Don't force HTTPS redirect as Railway handles this
    # SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shop',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR.parent, 'frontend', 'dist', 'spa'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Railway PostgreSQL Database (Postgres-kz93)
DATABASE_URL = os.getenv('DATABASE_URL')
USE_SQLITE = os.getenv('USE_SQLITE', 'False').lower() == 'true'

# Production Database Configuration
if not DEBUG or 'RENDER' in os.environ:
    # Force PostgreSQL in production or on Render
    DATABASE_URL = os.getenv('DATABASE_URL')
    USE_SQLITE = False
    print("Production environment detected - forcing PostgreSQL")
    
    if DATABASE_URL:
        try:
            import dj_database_url
            DATABASES['default'] = dj_database_url.parse(DATABASE_URL)
            
            # Add production database settings
            DATABASES['default'].update({
                'CONN_MAX_AGE': 600,  # Connection pooling
                'OPTIONS': {
                    'sslmode': 'require',  # Require SSL for production
                },
            })
            
            print(f"✅ Connected to PostgreSQL database: {DATABASES['default']['NAME']}")
            print(f"   Host: {DATABASES['default']['HOST']}")
            print(f"   Port: {DATABASES['default']['PORT']}")
            
        except Exception as e:
            print(f"❌ Failed to connect to PostgreSQL: {e}")
            print("🔄 This will cause deployment to fail - check DATABASE_URL")
            raise e
    else:
        print("❌ DATABASE_URL not found in environment variables")
        print("🔄 This will cause deployment to fail - set DATABASE_URL in Render")
        if not DEBUG:
            raise ValueError("DATABASE_URL is required in production")

elif DATABASE_URL and not USE_SQLITE:
    # Development with PostgreSQL
    try:
        import dj_database_url
        DATABASES['default'] = dj_database_url.parse(DATABASE_URL)
        print(f"🔧 Development: Using PostgreSQL from DATABASE_URL")
    except Exception as e:
        print(f"⚠️  Failed to connect to PostgreSQL: {e}")
        print(f"🔄 Falling back to SQLite database at: {DATABASES['default']['NAME']}")
else:
    # Development with SQLite
    print(f"🔧 Development: Using SQLite database at: {DATABASES['default']['NAME']}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Backend static files (admin CSS, etc.)
]

# Only add frontend static files if they exist (for local development)
frontend_static_path = os.path.join(BASE_DIR.parent, 'frontend', 'dist', 'spa')
if os.path.exists(frontend_static_path):
    STATICFILES_DIRS.append(frontend_static_path)

# WhiteNoise configuration - simplified for better compatibility
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Media files (User uploads)
MEDIA_URL = '/media/'

# Default file storage - use enhanced storage for better persistence
DEFAULT_FILE_STORAGE = 'shop.storage.DualLocationStorage'

# Media root configuration
if os.getenv('RENDER') or 'onrender.com' in os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''):
    # Render deployment - use persistent disk
    MEDIA_ROOT = '/opt/render/project/data/media'
    print(f"📁 Render: Media root set to: {MEDIA_ROOT}")
    
    # Ensure all media directories exist
    media_dirs = [
        MEDIA_ROOT,
        '/opt/render/project/data/media_backup',
        '/opt/render/project/data/media_archive',
        os.path.join(MEDIA_ROOT, 'products'),
        os.path.join(MEDIA_ROOT, 'categories'),
    ]
    
    for media_dir in media_dirs:
        os.makedirs(media_dir, exist_ok=True)
    
    print(f"📁 Media directories created and verified")
    
elif os.getenv('RAILWAY_ENVIRONMENT'):
    # Railway deployment - use persistent volume
    MEDIA_ROOT = '/app/data/media'
    print(f"📁 Railway: Media root set to: {MEDIA_ROOT}")
else:
    # Local development
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    print(f"📁 Local: Media root set to: {MEDIA_ROOT}")

# Ensure media root exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# CORS settings moved below - using CORS_ALLOW_ALL_ORIGINS for now

# Temporarily allow all origins for debugging
CORS_ALLOW_ALL_ORIGINS = True  # TODO: Change back to False after testing
CORS_ALLOWED_ORIGINS = []  # Clear this when using CORS_ALLOW_ALL_ORIGINS

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF settings for Railway, Render, and Vercel
CSRF_TRUSTED_ORIGINS = [
    "https://enontino-production.up.railway.app",
    "https://enintino.vercel.app",  # Main production frontend
    "https://enintino-a8265asrd-bassys-projects-fca17413.vercel.app",
    "https://enintino-1b440svfd-bassys-projects-fca17413.vercel.app",
    # Add Render domains
    "https://entstore-backend.onrender.com",
    "https://entstore-frontend.onrender.com",
    # Add Vercel domains
    "https://*.vercel.app",
    "https://ent-stores.vercel.app",
]

# Add frontend domain to CSRF trusted origins
FRONTEND_URL = os.getenv('FRONTEND_URL')
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

# Additional CSRF settings for Railway deployment
CSRF_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests
CSRF_COOKIE_DOMAIN = None  # Let Django handle the domain automatically
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF

# Session settings
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'

# For development, you can also use CORS_ALLOW_ALL_ORIGINS = True
# But the above specific origins are more secure
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Payment Settings
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# MTN MoMo Settings (Sandbox)
MOMO_SUBSCRIPTION_KEY = os.getenv('MOMO_SUBSCRIPTION_KEY')
MOMO_API_USER = os.getenv('MOMO_API_USER')
MOMO_API_KEY = os.getenv('MOMO_API_KEY')

# Email Configuration - Brevo SMTP
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Email addresses - Using your verified Brevo sender
DEFAULT_FROM_EMAIL = 'ENTstore <awuleynovember@gmail.com>'  # Your verified sender
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'Enontinoclothing@gmail.com')  # Your actual email for admin notifications
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Backup sender (the SMTP login email)
SMTP_FROM_EMAIL = 'ENTstore <81d61b003@smtp-brevo.com>'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'shop.payment_views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}