"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%)!&vi67urca4#$_4ia9fft9q_pc+h%5sjal2o!@a9%@f7@4vn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.1.104']

# Railway deployment - add Railway domains
RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
if RAILWAY_STATIC_URL:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)

RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Add known Railway domains
ALLOWED_HOSTS.extend([
    'enontino-production.up.railway.app',
    'encc-production.up.railway.app',  # New Railway domain
    '*.railway.app',
    '*.up.railway.app',
    'testserver'  # For testing
])

# Allow all hosts in production (Railway will handle the routing)
if not DEBUG:
    ALLOWED_HOSTS = ['*']

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Changed from DENY to allow admin frames
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Don't force HTTPS redirect as Railway handles this
    # SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shop',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR.parent, 'frontend', 'dist', 'spa'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Railway PostgreSQL Database Configuration
DATABASE_URL = os.getenv('DATABASE_URL')
DATABASE_INTERNAL_URL = os.getenv('DATABASE_INTERNAL_URL')
USE_SQLITE = os.getenv('USE_SQLITE', 'False').lower() == 'true'

# Determine which database URL to use
def get_database_url():
    """Get the appropriate database URL based on environment"""
    if os.getenv('RAILWAY_ENVIRONMENT'):
        # Use internal URL when running on Railway
        return DATABASE_INTERNAL_URL or DATABASE_URL
    else:
        # Use public URL for local development
        return DATABASE_URL

# Database configuration logic
if USE_SQLITE:
    # Explicitly use SQLite
    print(f"Development: Using SQLite database at: {DATABASES['default']['NAME']}")
elif DATABASE_URL:
    # Use PostgreSQL
    try:
        import dj_database_url
        db_url = get_database_url()
        DATABASES['default'] = dj_database_url.parse(db_url)
        
        # Add production database settings for Railway deployment
        if not DEBUG or os.getenv('RAILWAY_ENVIRONMENT'):
            DATABASES['default'].update({
                'CONN_MAX_AGE': 600,  # Connection pooling
                'OPTIONS': {
                    'sslmode': 'require',  # Require SSL for production
                },
            })
            print("Production: Using PostgreSQL with SSL and connection pooling")
        else:
            print("Development: Using PostgreSQL from DATABASE_URL")
            
        print(f"✅ Connected to PostgreSQL database: {DATABASES['default']['NAME']}")
        print(f"   Host: {DATABASES['default']['HOST']}")
        print(f"   Port: {DATABASES['default']['PORT']}")
        
    except Exception as e:
        print(f"❌ Failed to connect to PostgreSQL: {e}")
        print("🔄 Falling back to SQLite for now")
        # Keep SQLite as fallback
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # No DATABASE_URL provided, use SQLite
    print(f"Development: Using SQLite database at: {DATABASES['default']['NAME']}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Backend static files (admin CSS, etc.)
]

# Only add frontend static files if they exist (for local development)
frontend_static_path = os.path.join(BASE_DIR.parent, 'frontend', 'dist', 'spa')
if os.path.exists(frontend_static_path):
    STATICFILES_DIRS.append(frontend_static_path)

# WhiteNoise configuration - simplified for better compatibility
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Media files (User uploads)
MEDIA_URL = '/media/'

# Default file storage - use permanent cloud storage
DEFAULT_FILE_STORAGE = 'shop.cloud_storage.PermanentStorage'

# GitHub storage configuration (for permanent media storage)
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')  # Set this in Render environment
GITHUB_MEDIA_REPO = 'ENTstore-media'  # Create this repository

# Cloudinary configuration (optional, for additional redundancy)
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', 'entstore')

# Media root configuration for production
if not DEBUG:
    # Production deployment - use appropriate media path
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    print(f"📁 Render: Media root set to: {MEDIA_ROOT}")
    
    # Ensure all media directories exist
    media_dirs = [
        MEDIA_ROOT,
        '/opt/render/project/data/media_backup',
        '/opt/render/project/data/media_archive',
        os.path.join(MEDIA_ROOT, 'products'),
        os.path.join(MEDIA_ROOT, 'categories'),
    ]
    
    for media_dir in media_dirs:
        os.makedirs(media_dir, exist_ok=True)
    
    print(f"📁 Media directories created and verified")
    
elif os.getenv('RAILWAY_ENVIRONMENT'):
    # Railway deployment - use persistent volume
    MEDIA_ROOT = '/app/data/media'
    print(f"📁 Railway: Media root set to: {MEDIA_ROOT}")
else:
    # Local development
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    print(f"📁 Local: Media root set to: {MEDIA_ROOT}")

# Ensure media root exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# CORS settings moved below - using CORS_ALLOW_ALL_ORIGINS for now

# CORS Configuration
if DEBUG:
    # Development: Allow all origins for easier testing
    CORS_ALLOW_ALL_ORIGINS = True
    print("🌐 CORS: Allowing all origins for development")
else:
    # Production: Specific domains for security
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://www.enontinoclothingstore.com",
        "https://enontinoclothingstore.com",
        "https://enontino-production.up.railway.app",
        "https://encc-production.up.railway.app",  # New Railway domain
        "https://enintino.vercel.app",
        "https://enintino-a8265asrd-bassys-projects-fca17413.vercel.app",
        "https://enintino-1b440svfd-bassys-projects-fca17413.vercel.app",
        "https://ent-stores.vercel.app",
    ]
    print("🌐 CORS: Using specific allowed origins for production")

# Always allow local development origins
CORS_ALLOWED_ORIGINS_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://192\.168\.\d+\.\d+:\d+$",  # Local network
]

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'cache-control',
    'content-type',
    'dnt',
    'origin',
    'pragma',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-forwarded-for',
    'x-forwarded-proto',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Additional CORS settings for production
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    # Production domains
    "https://www.enontinoclothingstore.com",
    "https://enontinoclothingstore.com",
    "https://enontino-production.up.railway.app",
    "https://encc-production.up.railway.app",  # New Railway domain
    "https://enintino.vercel.app",
    "https://enintino-a8265asrd-bassys-projects-fca17413.vercel.app",
    "https://enintino-1b440svfd-bassys-projects-fca17413.vercel.app",
    "https://ent-stores.vercel.app",
    # Local development
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Add frontend domain to CSRF trusted origins
FRONTEND_URL = os.getenv('FRONTEND_URL')
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

# CSRF settings optimized for development and production
if DEBUG:
    # Development: More permissive CSRF settings
    CSRF_COOKIE_SECURE = False  # Allow non-HTTPS in development
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access
    CSRF_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests
    CSRF_COOKIE_DOMAIN = None  # Auto-detect domain
    CSRF_USE_SESSIONS = False  # Use cookies for CSRF tokens
    # Disable CSRF for API endpoints in development (if needed)
    # CSRF_EXEMPT_URLS = [r'^/api/.*$']  # Uncomment if you have API endpoints
else:
    # Production: Secure CSRF settings
    CSRF_COOKIE_SECURE = True  # Require HTTPS
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for frontend
    CSRF_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests
    CSRF_COOKIE_DOMAIN = None  # Let Django handle domain
    CSRF_USE_SESSIONS = False  # Use cookies for CSRF tokens

# Session settings
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'

# For development, you can also use CORS_ALLOW_ALL_ORIGINS = True
# But the above specific origins are more secure

# Payment Settings
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# MTN MoMo Settings (Sandbox)
MOMO_SUBSCRIPTION_KEY = os.getenv('MOMO_SUBSCRIPTION_KEY')
MOMO_API_USER = os.getenv('MOMO_API_USER')
MOMO_API_KEY = os.getenv('MOMO_API_KEY')

# Email Configuration - Brevo SMTP
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Email addresses - Using verified Brevo sender
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'ENTstore <awuleynovember@gmail.com>')  # Use verified Brevo sender
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'Enontinoclothing@gmail.com')  # Your actual email for admin notifications
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Reply-to email (your business email)
REPLY_TO_EMAIL = 'Enontinoclothing@gmail.com'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'shop.payment_views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}